-- Create Verified Jobs Table
create table verified_jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  url text not null,
  score int not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Reports Table
create table reports (
  id bigint generated by default as identity primary key,
  job_url text not null,
  reason text not null, -- 'ghosted', 'fake', 'rejection_speed'
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table verified_jobs enable row level security;
alter table reports enable row level security;

-- Create Policies (Public Read/Write for Demo)
-- In production, you would restrict Write to authenticated users or backend.
create policy "Public jobs are viewable by everyone."
  on verified_jobs for select
  using ( true );

create policy "Anon can insert reports"
  on reports for insert
  with check ( true );

create policy "Public reports are viewable by everyone"
  on reports for select
  using ( true );
